before:
  hooks:
    - go mod tidy
builds:
  - id: "sonic-android-supply"
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath=C:/Users/ZHOUYIXUN/Desktop/sonic-android-supply
    gcflags:
      - all=-trimpath=C:/Users/ZHOUYIXUN/Desktop/sonic-android-supply
    ldflags:
      - -s -w
    main: .
    binary: sas
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
archives:
  - replacements:
      darwin: macosx
      linux: linux
      windows: windows
      386: x86
      amd64: x86_64
